CREATE SCHEMA VITRSA_SANDBOX;

 CREATE SEQUENCE VITRSA_SANDBOX.VIT_RSA_GENERIC_SEQ
     START WITH 5002
     INCREMENT BY 1;

 CREATE TABLE VITRSA_SANDBOX.ACCOUNT_TYPE
  (
     ACCOUNT_TYPE_ID BIGINT  NOT NULL,
     MNEMONIC    VARCHAR (100) NOT NULL UNIQUE ,
     ACCOUNT_TYPE_NAME   VARCHAR (255) NOT NULL,
     CREATION_DATE   DATE NOT NULL,
     PRIMARY KEY (ACCOUNT_TYPE_ID)
 );
 CREATE TABLE VITRSA_SANDBOX.ACCOUNT_TX_DETAILS
 (
     TX_ID BIGINT NOT NULL,
     ACCOUNT_TYPE_ID BIGINT  NOT NULL,
     MEMBER_ID BIGINT  NOT NULL,
     AMOUNT BIGINT  NOT NULL,
     TX_DATE  DATE NOT NULL,
     PRIMARY KEY(TX_ID),
     CONSTRAINT  TX_ACCOUNT_TYPE_IDL FOREIGN  KEY (ACCOUNT_TYPE_ID) REFERENCES VITRSA_SANDBOX.ACCOUNT_TYPE(ACCOUNT_TYPE_ID, MNEMONIC, ACCOUNT_TYPE_NAME, CREATION_DATE)
 );
